### ISSUE TITLE
Not working for DASH

### ISSUE THREAD

**Issue by alexandrevicenzi** [videojs/videojs-contrib-quality-levels#43]
## Description

This plugin has no support for DASH streams.

If there's no intention to add DASH or any other format in this plugin it should be renamed to `videojs-contrib-hls-quality-levels` for example.

## Steps to reproduce

Play this video https://bitdash-a.akamaihd.net/content/sintel/sintel.mpd and try to call `player.qualityLevels()`.

## Results

`player.qualityLevels()` returns an empty list.

### Actual

It should return available quality levels.

### Error output

None.

#### videojs

7.0.5

#### browsers

All

#### OSes

All

### plugins

dash-contrib

**Comment by squarebracket** [comment]
This plugin isn't meant for particular kinds of streams per se; it presents a common API which other plugins can adopt so that _yet other_ plugins can then use that information when available.

dash.js' way of doing things means that the full API can't be _totally_ implemented, which I imagine is why support hasn't been merged into contrib-dash. That being said, you do have some options:
1. Use [VHS](https://github.com/videojs/http-streaming), which is built into video.js 7
2. Use [this PR](https://github.com/videojs/videojs-contrib-dash/pull/162), which implements support in contrib-dash
3. Use something like [this patch](https://gist.github.com/squarebracket/7bf48036a5e8c74d2dd51e8ebd621a28), which implements support in contrib-dash
